ERROR 2022-06-02 14:46:00,737 log 16148 13784 Internal Server Error: /article/article-detail/6/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 232, in get_cached_trees
    parent_attr = queryset[0]._mptt_meta.parent_attr
AttributeError: 'Comment' object has no attribute '_mptt_meta'
ERROR 2022-06-02 14:50:09,089 log 17088 5816 Internal Server Error: /article/article-detail/5/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 232, in get_cached_trees
    parent_attr = queryset[0]._mptt_meta.parent_attr
AttributeError: 'Comment' object has no attribute '_mptt_meta'
ERROR 2022-06-02 14:50:15,694 log 17088 5816 Internal Server Error: /article/article-detail/5/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 232, in get_cached_trees
    parent_attr = queryset[0]._mptt_meta.parent_attr
AttributeError: 'Comment' object has no attribute '_mptt_meta'
ERROR 2022-06-02 15:04:27,942 log 3380 8104 Internal Server Error: /article/article-detail/5/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 232, in get_cached_trees
    parent_attr = queryset[0]._mptt_meta.parent_attr
AttributeError: 'Comment' object has no attribute '_mptt_meta'
ERROR 2022-06-02 15:11:26,453 log 1696 12912 Internal Server Error: /article/article-detail/15/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: comment_comment.lft

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 230, in get_cached_trees
    if queryset:
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\query.py", line 278, in __bool__
    self._fetch_all()
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: comment_comment.lft
ERROR 2022-06-02 15:15:06,541 log 5692 15736 Internal Server Error: /article/article-detail/15/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 232, in get_cached_trees
    parent_attr = queryset[0]._mptt_meta.parent_attr
AttributeError: 'Comment' object has no attribute '_mptt_meta'
ERROR 2022-06-02 15:15:11,574 log 5692 15736 Internal Server Error: /article/article-detail/15/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 232, in get_cached_trees
    parent_attr = queryset[0]._mptt_meta.parent_attr
AttributeError: 'Comment' object has no attribute '_mptt_meta'
ERROR 2022-06-02 15:15:18,243 log 5692 15736 Internal Server Error: /article/article-detail/6/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 232, in get_cached_trees
    parent_attr = queryset[0]._mptt_meta.parent_attr
AttributeError: 'Comment' object has no attribute '_mptt_meta'
ERROR 2022-06-02 15:15:25,106 log 5692 15736 Internal Server Error: /article/article-detail/6/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 232, in get_cached_trees
    parent_attr = queryset[0]._mptt_meta.parent_attr
AttributeError: 'Comment' object has no attribute '_mptt_meta'
ERROR 2022-06-02 15:19:03,510 log 2648 3412 Internal Server Error: /article/article-detail/14/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: comment_comment.lft

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 230, in get_cached_trees
    if queryset:
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\query.py", line 278, in __bool__
    self._fetch_all()
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: comment_comment.lft
ERROR 2022-06-02 15:19:07,599 log 2648 3412 Internal Server Error: /article/article-detail/15/
Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: comment_comment.lft

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\django_project\my_blog\article\views.py", line 102, in article_detail
    return render(request, 'article/detail.html', context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 257, in render
    roots = cache_tree_children(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\templatetags\mptt_tags.py", line 236, in cache_tree_children
    return get_cached_trees(queryset)
  File "E:\django_project\my_blog\venv\lib\site-packages\mptt\utils.py", line 230, in get_cached_trees
    if queryset:
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\query.py", line 278, in __bool__
    self._fetch_all()
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\django_project\my_blog\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: comment_comment.lft
